const INITIAL_DATA = 'INITIAL_DATA';
const ADD_MESSAGE = 'ADD_MESSAGE';
const ADD_USER = 'ADD_USER';
const USERS_LIST = 'USERS_LIST';
const NEW_USER_CONNECTED = 'NEW_USER_CONNECTED';
const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
const USER_DISCONECTED = 'USER_DISCONECTED';
const USER_INTIALIZATION_START = 'USER_INTIALIZATION_START';
const USER_INTIALIZATION_FINISH = 'USER_INTIALIZATION_FINISH';
const ERROR_RECEIVED = 'ERROR_RECEIVED';
const SHOW_DEBUG = 'SHOW_DEBUG';
const HIDE_DEBUG = 'HIDE_DEBUG';
const SIDEBAR_TOGGLER = 'SIDEBAR_TOGGLER';
const HIDE_DEBUG_MANUAL = 'HIDE_DEBUG_MANUAL';
const SOMEONE_TYPING = 'SOMEONE_TYPING';
const USER_TYPING = 'USER_TYPING';
const SELECT_CURRENT_CHAT = 'SELECT_CURRENT_CHAT';
const CHAT_SELECTED = 'CHAT_SELECTED';
const CREATE_NEW_CHAT = 'CREATE_NEW_CHAT';
const NEW_CHAT_CREATED = 'NEW_CHAT_CREATED';
const HIDE_SIDEBAR = 'HIDE_SIDEBAR';
const SET_FAVORITE = 'SET_FAVORITE';
const FAVORITE_CHANNEL_SETTED = 'FAVORITE_CHANNEL_SETTED';
const FAVORIVE_CHANNEL_ADDED = 'FAVORIVE_CHANNEL_ADDED';

export {
  INITIAL_DATA,
  ADD_MESSAGE,
  ADD_USER,
  USERS_LIST,
  NEW_USER_CONNECTED,
  MESSAGE_RECEIVED,
  USER_DISCONECTED,
  USER_INTIALIZATION_START,
  USER_INTIALIZATION_FINISH,
  ERROR_RECEIVED,
  SHOW_DEBUG,
  HIDE_DEBUG,
  SIDEBAR_TOGGLER,
  HIDE_DEBUG_MANUAL,
  SOMEONE_TYPING,
  USER_TYPING,
  SELECT_CURRENT_CHAT,
  CHAT_SELECTED,
  CREATE_NEW_CHAT,
  NEW_CHAT_CREATED,
  HIDE_SIDEBAR,
  SET_FAVORITE,
  FAVORITE_CHANNEL_SETTED,
  FAVORIVE_CHANNEL_ADDED
};
