// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'closeButton': string;
  'container': string;
  'customCheckbox': string;
  'disabledCursor': string;
  'error': string;
  'fetchSpinner': string;
  'flexCenter': string;
  'form': string;
  'formButton': string;
  'formButtonActive': string;
  'formElementWrap': string;
  'formInput': string;
  'formInputDisabled': string;
  'formWrap': string;
  'headlineText': string;
  'label': string;
  'labelEmail': string;
  'labelPassword': string;
  'labelText': string;
  'loginHeadline': string;
  'rememberContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
