const INITIAL_DATA = 'INITIAL_DATA';
const ADD_USER = 'ADD_USER';
const ADD_MESSAGE = 'ADD_MESSAGE';
const REMOVE_USER = 'REMOVE_USER';
const USERS_LIST = 'USERS_LIST';
const SOMEONE_TYPING = 'SOMEONE_TYPING';
const CREATE_NEW_CHAT = 'CREATE_NEW_CHAT';
const NEW_CHAT_CREATED = 'NEW_CHAT_CREATED';

module.exports = {
  INITIAL_DATA,
  ADD_USER,
  ADD_MESSAGE,
  REMOVE_USER,
  USERS_LIST,
  SOMEONE_TYPING,
  CREATE_NEW_CHAT,
  NEW_CHAT_CREATED
};
